Fix publishing packaging ERROR
The CI pipeline previously failed to publish the package
to PyPI because of a direct dependency on a git repository.

HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
Can't have direct dependency: frequenz-api-electricity-trading@
git+https://github.com/frequenz-floss/frequenz-api-electricity-trading@
8d89155. See https://packaging.python.org/specifications/core-metadata
for more information.

Signed-off-by: Daniel Zullo <daniel.zullo@frequenz.com>